spring:
  rabbitmq:
    username: mqadmin
    password: Admin123XX_
    host: 10.121.2.211
  profiles:
    active: usage_message

logging:
  level:
    org: ERROR

tutorial:
  client:
    duration: 10000